# Generated by Django 3.0 on 2021-02-19 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acccat',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=1, primary_key=True, serialize=False)),
                ('type', models.CharField(db_column='Type', max_length=15)),
            ],
            options={
                'db_table': 'AccCat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('username', models.CharField(db_column='Username', max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(db_column='Password', max_length=32)),
            ],
            options={
                'db_table': 'Account',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('num', models.IntegerField(db_column='Num')),
                ('street', models.CharField(db_column='Street', max_length=15)),
                ('ward', models.CharField(blank=True, db_column='Ward', max_length=15, null=True)),
                ('district', models.CharField(blank=True, db_column='District', max_length=15, null=True)),
                ('city', models.CharField(db_column='City', max_length=15)),
                ('province', models.CharField(blank=True, db_column='Province', max_length=15, null=True)),
                ('phonenumber', models.CharField(db_column='PhoneNumber', max_length=15)),
            ],
            options={
                'db_table': 'Address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=20)),
                ('author', models.CharField(blank=True, db_column='Author', max_length=20, null=True)),
                ('publisher', models.CharField(blank=True, db_column='Publisher', max_length=20, null=True)),
                ('year', models.IntegerField(blank=True, db_column='Year', null=True)),
                ('stock', models.SmallIntegerField(blank=True, db_column='Stock', null=True)),
            ],
            options={
                'db_table': 'Book',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=30, null=True)),
            ],
            options={
                'db_table': 'Category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Deliveryinfo',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('status', models.CharField(db_column='Status', max_length=20)),
            ],
            options={
                'db_table': 'DeliveryInfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('dateorder', models.DateTimeField(blank=True, db_column='DateOrder', null=True)),
                ('paid', models.BooleanField(db_column='Paid')),
                ('totalprice', models.DecimalField(blank=True, db_column='TotalPrice', decimal_places=4, max_digits=19, null=True)),
            ],
            options={
                'db_table': 'Orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('method', models.CharField(db_column='Method', max_length=20)),
            ],
            options={
                'db_table': 'Payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, db_column='FirstName', max_length=10, null=True)),
                ('middlename', models.CharField(blank=True, db_column='MiddleName', max_length=10, null=True)),
                ('lastname', models.CharField(blank=True, db_column='LastName', max_length=10, null=True)),
                ('dob', models.DateField(blank=True, db_column='DoB', null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=30, null=True)),
                ('gender', models.CharField(blank=True, db_column='Gender', max_length=1, null=True)),
            ],
            options={
                'db_table': 'Person',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('datein', models.DateTimeField(blank=True, db_column='DateIn', null=True)),
            ],
            options={
                'db_table': 'Stock',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.SmallIntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('amount', models.IntegerField(blank=True, db_column='Amount', null=True)),
            ],
            options={
                'db_table': 'Voucher',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vouchercategory',
            fields=[
                ('id', models.SmallIntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=20)),
            ],
            options={
                'db_table': 'VoucherCategory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bookcategory',
            fields=[
                ('bookid', models.OneToOneField(db_column='BookID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='home.Book')),
            ],
            options={
                'db_table': 'BookCategory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orderdelivery',
            fields=[
                ('orderid', models.OneToOneField(db_column='OrderID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='home.Orders')),
                ('time', models.DateTimeField(blank=True, db_column='Time', null=True)),
            ],
            options={
                'db_table': 'OrderDelivery',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orderdetail',
            fields=[
                ('orderid', models.OneToOneField(db_column='OrderID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='home.Orders')),
                ('amount', models.SmallIntegerField(db_column='Amount')),
                ('unitprice', models.DecimalField(blank=True, db_column='UnitPrice', decimal_places=4, max_digits=19, null=True)),
            ],
            options={
                'db_table': 'OrderDetail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stockdetail',
            fields=[
                ('stockid', models.OneToOneField(db_column='StockID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='home.Stock')),
                ('amount', models.SmallIntegerField(blank=True, db_column='Amount', null=True)),
            ],
            options={
                'db_table': 'StockDetail',
                'managed': False,
            },
        ),
    ]
